import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AttendanceRecord } from '../types/attendance';

export interface PDFExportOptions {
  title?: string;
  subtitle?: string;
  generatedBy?: string;
}

export function generateAttendancePDF(
  records: AttendanceRecord[],
  options: PDFExportOptions = {}
) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const title = options.title || 'Smart Campus Attendance Report';
  const subtitle = options.subtitle || 'Swarna Bharathi Institute of Science and Technology (SBIT)';

  // Header Banner
  doc.setFillColor(30, 58, 138); // SBIT Blue
  doc.rect(0, 0, 297, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 12);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(subtitle, 14, 19);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 283, 12, { align: 'right' });
  if (options.generatedBy) {
    doc.text(`Generated By: ${options.generatedBy}`, 283, 19, { align: 'right' });
  }

  // Summary Metrics Bar
  const total = records.length;
  const present = records.filter(r => r.status === 'present').length;
  const late = records.filter(r => r.status === 'late').length;
  const absent = records.filter(r => r.status === 'absent').length;
  const pct = total > 0 ? Math.round(((present + late) / total) * 100) : 0;

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Records: ${total}   |   Present: ${present}   |   Late: ${late}   |   Absent: ${absent}   |   Attendance Rate: ${pct}%`, 14, 34);

  // Table Data
  const tableHead = [
    [
      'Date',
      'Time',
      'Student Name',
      'Hall Ticket No',
      'Branch',
      'Sec',
      'Year',
      'Subject',
      'Faculty',
      'Status',
      'Method'
    ]
  ];

  const tableBody = records.map(rec => {
    const d = new Date(rec.markedAt);
    return [
      d.toLocaleDateString(),
      d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      rec.studentName,
      rec.hallTicketNo,
      rec.branch,
      rec.section,
      rec.year,
      rec.subject,
      rec.facultyName,
      rec.status.toUpperCase(),
      rec.verificationMethod === 'qr_gps' ? 'QR + GPS' : 'Manual'
    ];
  });

  autoTable(doc, {
    startY: 38,
    head: tableHead,
    body: tableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold',
      halign: 'center'
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [51, 65, 85]
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    columnStyles: {
      9: { fontStyle: 'bold', halign: 'center' }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 9) {
        const val = String(data.cell.raw);
        if (val === 'PRESENT') {
          data.cell.styles.textColor = [16, 185, 129]; // emerald
        } else if (val === 'LATE') {
          data.cell.styles.textColor = [245, 158, 11]; // amber
        } else if (val === 'ABSENT') {
          data.cell.styles.textColor = [239, 68, 68]; // red
        }
      }
    }
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      'Swarna Bharathi Institute of Science and Technology (SBIT) - Smart Campus Attendance Platform',
      14,
      202
    );
    doc.text(`Page ${i} of ${pageCount}`, 283, 202, { align: 'right' });
  }

  doc.save(`SBIT_Attendance_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}
